enum types { 
    ADD_SHIPMENT = 'ADD_SHIPMENT',
    REMOVE_SHIPMENT = 'REMOVE_SHIPMENT',
    ADD_LABEL = 'ADD_LABEL',
    REMOVE_LABEL = 'REMOVE_LABEL',
    UI_SET_ERROR = 'UI_SET_ERROR',
    UI_REMOVE_ERROR = 'UI_REMOVE_ERROR',
    UI_SET_LOADING = 'UI_SET_LOADING',
    UI_REMOVE_LOADING = 'UI_REMOVE_LOADING',
    SET_RATES = 'SET_RATES',
    REMOVE_RATES = 'REMOVE_RATES'
} 

export default types